#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays this data in the specified format using awk

awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' apache-access.log | sort -nr | awk '{ printf "%6s %s %s\n", $1, $2, $3 }'